# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VKk8KqGrMhfBVR72BoJJv_E602BoWM3
"""

# Install dependencies if needed
!pip install diffusers[torch] torch torchvision torchaudio nest_asyncio

import nest_asyncio
from diffusers import StableDiffusionPipeline
import torch
from io import BytesIO
import base64

# Allow nested async calls in Jupyter/Colab
nest_asyncio.apply()

# Load Stable Diffusion
pipeline = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)